require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NewspostAttachmentsController do

  # This should return the minimal set of attributes required to create a valid
  # NewspostAttachment. As you add validations to NewspostAttachment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "newspost_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NewspostAttachmentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all newspost_attachments as @newspost_attachments" do
      newspost_attachment = NewspostAttachment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:newspost_attachments).should eq([newspost_attachment])
    end
  end

  describe "GET show" do
    it "assigns the requested newspost_attachment as @newspost_attachment" do
      newspost_attachment = NewspostAttachment.create! valid_attributes
      get :show, {:id => newspost_attachment.to_param}, valid_session
      assigns(:newspost_attachment).should eq(newspost_attachment)
    end
  end

  describe "GET new" do
    it "assigns a new newspost_attachment as @newspost_attachment" do
      get :new, {}, valid_session
      assigns(:newspost_attachment).should be_a_new(NewspostAttachment)
    end
  end

  describe "GET edit" do
    it "assigns the requested newspost_attachment as @newspost_attachment" do
      newspost_attachment = NewspostAttachment.create! valid_attributes
      get :edit, {:id => newspost_attachment.to_param}, valid_session
      assigns(:newspost_attachment).should eq(newspost_attachment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NewspostAttachment" do
        expect {
          post :create, {:newspost_attachment => valid_attributes}, valid_session
        }.to change(NewspostAttachment, :count).by(1)
      end

      it "assigns a newly created newspost_attachment as @newspost_attachment" do
        post :create, {:newspost_attachment => valid_attributes}, valid_session
        assigns(:newspost_attachment).should be_a(NewspostAttachment)
        assigns(:newspost_attachment).should be_persisted
      end

      it "redirects to the created newspost_attachment" do
        post :create, {:newspost_attachment => valid_attributes}, valid_session
        response.should redirect_to(NewspostAttachment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved newspost_attachment as @newspost_attachment" do
        # Trigger the behavior that occurs when invalid params are submitted
        NewspostAttachment.any_instance.stub(:save).and_return(false)
        post :create, {:newspost_attachment => { "newspost_id" => "invalid value" }}, valid_session
        assigns(:newspost_attachment).should be_a_new(NewspostAttachment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NewspostAttachment.any_instance.stub(:save).and_return(false)
        post :create, {:newspost_attachment => { "newspost_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested newspost_attachment" do
        newspost_attachment = NewspostAttachment.create! valid_attributes
        # Assuming there are no other newspost_attachments in the database, this
        # specifies that the NewspostAttachment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        NewspostAttachment.any_instance.should_receive(:update).with({ "newspost_id" => "1" })
        put :update, {:id => newspost_attachment.to_param, :newspost_attachment => { "newspost_id" => "1" }}, valid_session
      end

      it "assigns the requested newspost_attachment as @newspost_attachment" do
        newspost_attachment = NewspostAttachment.create! valid_attributes
        put :update, {:id => newspost_attachment.to_param, :newspost_attachment => valid_attributes}, valid_session
        assigns(:newspost_attachment).should eq(newspost_attachment)
      end

      it "redirects to the newspost_attachment" do
        newspost_attachment = NewspostAttachment.create! valid_attributes
        put :update, {:id => newspost_attachment.to_param, :newspost_attachment => valid_attributes}, valid_session
        response.should redirect_to(newspost_attachment)
      end
    end

    describe "with invalid params" do
      it "assigns the newspost_attachment as @newspost_attachment" do
        newspost_attachment = NewspostAttachment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NewspostAttachment.any_instance.stub(:save).and_return(false)
        put :update, {:id => newspost_attachment.to_param, :newspost_attachment => { "newspost_id" => "invalid value" }}, valid_session
        assigns(:newspost_attachment).should eq(newspost_attachment)
      end

      it "re-renders the 'edit' template" do
        newspost_attachment = NewspostAttachment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NewspostAttachment.any_instance.stub(:save).and_return(false)
        put :update, {:id => newspost_attachment.to_param, :newspost_attachment => { "newspost_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested newspost_attachment" do
      newspost_attachment = NewspostAttachment.create! valid_attributes
      expect {
        delete :destroy, {:id => newspost_attachment.to_param}, valid_session
      }.to change(NewspostAttachment, :count).by(-1)
    end

    it "redirects to the newspost_attachments list" do
      newspost_attachment = NewspostAttachment.create! valid_attributes
      delete :destroy, {:id => newspost_attachment.to_param}, valid_session
      response.should redirect_to(newspost_attachments_url)
    end
  end

end
